version: '3.9'

services:
  transcendence:
    container_name: frontend
    build:
      context: frontend
      args:
        VITE_CLIENT_ID: ba3d391399909e1abe4166962a096cbc7c4f8bb9c55a66e764d63fac14521ffc
        VITE_REDIRECT_URI: https://localhost 
        VITE_BACKEND_URI: https://localhost
        BACKEND_INTERNAL_URI: nestjs:3000
    restart: always
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - avatars:/files
      - caddy_data:/data
      - caddy_config:/config

  db:
    container_name: postgresql
    restart: always
    image: postgres:14.4-alpine
    networks:
      - db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env.postgres

  backend:
    depends_on:
      - db
    container_name: nestjs
    restart: always
    build: backend
    networks:
      - db
      - web
    volumes:
      - avatars:/files
    env_file:
      - .env.backend

volumes:
  db: { }
  avatars: { }
  caddy_data: {}
  caddy_config: {}

networks:
  db:
  web:
