version: '3.9'

services:
  transcendence:
    container_name: transcendence
    build: frontend
    restart: always
    networks:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - avatars:/files
      - caddy_data:/data
      - caddy_config:/config

  db:
    container_name: postgresql
    restart: always
    image: postgres:14.4-alpine
    networks:
      - db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env.postgres

  nestjs:
    depends_on:
      - db
    container_name: nestjs
    restart: always
    build: backend
    networks:
      - db
      - web
    volumes:
      - avatars:/files
    env_file:
      - .env.backend

volumes:
  db: { }
  avatars: { }
  caddy_data: {}
  caddy_config: {}

networks:
  db:
  web:
