name: Build and push docker images

on:
  push:
    branches:
      - main

jobs:

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: 'backend/yarn.lock'
      - run: yarn install --immutable
      - run: yarn run build
      - uses: actions/upload-artifact@v3
        with:
          name: backend-dist
          path: backend/dist/

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: 'backend/yarn.lock'
      - run: yarn install --immutable
      - run: yarn run build
        env:
          VITE_REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          VITE_CLIENT_ID: ${{ secrets.CIENT_ID }}
          VITE_BACKEND_URI: ${{ secrets.BACKEND_URI }}

      - uses: actions/upload-artifact@v3
        with:
          name: frontend-dist
          path: frontend/dist/

  # Build backend docker image
  docker-backend:
    runs-on: ubuntu-latest
    needs: [ build-backend ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: backend-dist
          path: backend/dist/
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SPEED=1000
      - uses: docker/build-push-action@v3
        with:
          context: backend
          platforms: linux/amd64
          push: true
          tags: ghcr.io/nogesma/ft_transcendence_backend:latest

  # Build frontend docker image
  docker-frontend:
    runs-on: ubuntu-latest
    needs: [ build-frontend ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: frontend-dist
          path: frontend/dist/
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SPEED=1000
      - uses: docker/build-push-action@v3
        with:
          context: frontend
          platforms: linux/amd64
          push: true
          tags: ghcr.io/nogesma/ft_transcendence_frontend:latest
