name: Build and push docker images

on:
  push:
    branches:
      - main

jobs:

  docker-backend:
    runs-on: ubuntu-latest
    needs: [ build-backend ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: backend
          platforms: linux/amd64
          push: true
          tags: ghcr.io/nogesma/ft_transcendence_backend:latest

  docker-frontend:
    runs-on: ubuntu-latest
    needs: [ build-frontend ]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          context: frontend
          platforms: linux/amd64
          push: true
          tags: ghcr.io/nogesma/ft_transcendence_frontend:latest
